# Generated by Django 2.1.4 on 2019-02-02 08:13

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Category', models.CharField(choices=[('North Indian', 'North Indian'), ('North-Eastern', 'North-Easten'), ('Rajasthani', 'Rajasthani'), ('Gujarati', 'Gujarati'), ('South Indian', 'South Indian'), ('Continental', 'Continental'), ('Chinese', 'Chinese'), ('Italian', 'Italian')], max_length=15)),
                ('Ingredient', models.TextField()),
                ('Steps', models.TextField()),
                ('Image', models.ImageField(default='none.jpg', upload_to='')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Slug', autoslug.fields.AutoSlugField()),
            ],
            options={
                'verbose_name_plural': 'Recipes',
            },
        ),
    ]
